/** AUTO-GENERATED by JCEF TypeScriptObjectProcessor – DO NOT EDIT **/
import type {ResponseType} from './ResponseType';
import {ResponseValueConverter} from "./ResponseValueConverter";

export class CefQueryService {
    static request<T>(
        className: string,
        methodName: string,
        parameters: object,
        responseType: ResponseType = 'auto'
    ): Promise<T> {
        const request = JSON.stringify({className, methodName, parameters});
        return new Promise((resolve, reject) => {
            window.cefQuery({
                request,
                persistent: false,
                onSuccess: payload => {
                    let result = ResponseValueConverter.convert(payload, responseType);
                    resolve(result);
                },
                onFailure: err => reject(err),
            });
        });
    }
}
