/** AUTO-GENERATED by JCEF TypeScriptObjectProcessor – DO NOT EDIT **/
/**
 * Allowed response types for parsing CEF query results.
 */
export type ResponseType = 'auto' | 'string' | 'number' | 'boolean' | 'object';