/** AUTO-GENERATED by JCEF TypeScriptObjectProcessor – DO NOT EDIT **/
import { CefQueryService } from './CefQueryService';
import type { ComplexType2 } from './ComplexType2';
import type { ComplexType3 } from '../io/github/bitfist/jcef/spring/example/ComplexType3';

export class SomeJavaScriptObject {
    public static something(id: number, name: string, aByte: number, type2: ComplexType2): Promise<ComplexType3> {
        return CefQueryService.request('io.github.bitfist.jcef.spring.example.SomeJavaScriptObject', 'something', {id, name, aByte, type2}, 'object');
    }

}
